name: test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y gcc-14 libx11-dev
      - run: make test CC=gcc-14
      - run: make CC=gcc-14

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          release: false
          install: make mingw-w64-ucrt-x86_64-gcc
      - run: make test
      - run: make
